apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-script
data:
  script.js: |
    import http from 'k6/http';
    export const options = {
      scenarios: {
        reads: {
          executor: 'constant-arrival-rate',
          duration: '60s',
          preAllocatedVUs: 2000,
          rate: 1000,
          timeUnit: '1s',
        }
      },
    };
    export default function read_per_sec() {
      http.get("http://petclinic:80/owners/1")
    }
---
apiVersion: batch/v1
kind: Job
metadata:
  name: k6
spec:
  backoffLimit: 3
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: grafanak6
          image: grafana/k6
          command: ["k6", "run", "/scripts/script.js"]
          volumeMounts:
            - name: k6-script
              mountPath: /scripts
      volumes:
        - name: k6-script
          configMap:
            name: k6-script
