alertmanager:
  enabled: false

grafana:
  adminPassword: "admin"
  defaultDashboardsEnabled: false

prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    podMonitorSelectorNilUsesHelmValues: false
